language: csharp

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    # Ubuntu 14.04
    - os: linux 
      dist: trusty
      sudo: required
      dotnet: "1.0.1"
      env: DOTNET_SDK_URL=https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.1/dotnet-dev-ubuntu-x64.latest.tar.gz
    # OSX 10.11
    - os: osx 
      #osx_image: xcode7.2
      mono: 4.8.0
      dotnet: "1.0.1"
      env: DOTNET_SDK_URL=https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.1/dotnet-dev-osx-x64.latest.tar.gz
  allow_failures:
    - os: osx

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force openssl ; fi

install:
  # Download .NET Core SDK and add to PATH
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
  - mkdir -p "$DOTNET_INSTALL_DIR"
  - curl -L "$DOTNET_SDK_URL" | tar -xzv -C "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
   
# Build netcore packages
script:
  - dotnet --info
  - cd src/fssrgen
  - dotnet restore
  - dotnet pack -c Release --output "../../bin/packages"
  - cd ../FSharp.SRGen.Build.Tasks
  - dotnet restore
  - dotnet pack -c Release --output "../../bin/packages"
  - cd ../dotnet-fssrgen
  - dotnet restore
  - dotnet pack -c Release --output "../../bin/packages"